# Generated by Django 4.1.7 on 2023-03-04 01:31

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringevent",
            name="recurrences",
            field=recurrence.fields.RecurrenceField(blank=True),
        ),
    ]
